const express=require("express")
const ConnectDB = require("./Config/ConnectDB")
const userRouter = require("./Routes/User")
const postRouter = require("./Routes/Post")
const commentRouter = require("./Routes/Comment")
const app=express()
require("dotenv").config()
ConnectDB()
app.use(express.json())
app.use("/api/users",userRouter)
app.use("/api/posts",postRouter)
app.use("/api/comments",commentRouter)
app.use((req,res)=>{
   res.send("API IS RUNNING ...") 
})
const port = process.env.port || 7666
app.listen(process.env.port,console.log(`server is running on ${process.env.port}`))